import SwiftUI
import SwiftData

struct GymView: View {
    @EnvironmentObject private var appState: AppState
    @Environment(\.modelContext) private var context
    @Query private var plans: [WorkoutPlan]
    @Query private var exercises: [ExerciseDefinition]
    @Query private var plannedExercises: [PlannedWorkoutExercise]
    @Query private var plannedSessions: [PlannedWorkoutSession]
    @Query private var sessions: [WorkoutRecord]
    @Query private var logs: [CompletedExerciseLog]
    @StateObject private var viewModel = GymViewModel()
    @State private var editor: GymEditorTarget?
    @State private var deletion: GymEditorTarget?
    @FocusState private var searchFocused: Bool
    private var summary: GymSummary { viewModel.summary(sessions: sessions, logs: logs, planned: plannedSessions) }

    var body: some View {
        VStack(spacing: 0) {
            TerminalHeader(titleKey: "route.gym", subtitleKey: "gym.subtitle", onBack: appState.goHome)
            HStack(spacing: 0) { sidebar; Divider().overlay(TerminalTokens.border); VStack(spacing: 0) { toolbar; content } }
            if let error = viewModel.errorMessage { Label(error, systemImage: "xmark.octagon").foregroundStyle(TerminalTokens.error).padding(.horizontal, 12).frame(maxWidth: .infinity, minHeight: 28, alignment: .leading).background(TerminalTokens.surface) } else { TerminalStatusBar(messageKey: viewModel.statusMessageKey) }
        }
        .sheet(item: $editor) { target in editorView(target) }
        .confirmationDialog("delete.confirm.title", isPresented: Binding(get: { deletion != nil }, set: { if !$0 { deletion = nil } })) { Button("action.delete", role: .destructive, action: confirmDelete); Button("action.cancel", role: .cancel) { deletion = nil } } message: { Text("delete.confirm.message") }
        .onReceive(NotificationCenter.default.publisher(for: .nexusNewItem)) { _ in createNew() }
        .onReceive(NotificationCenter.default.publisher(for: .nexusFocusSearch)) { _ in searchFocused = true }
        .accessibilityIdentifier("gym.screen")
    }
    private var sidebar: some View { VStack(alignment: .leading, spacing: 4) { ForEach(GymSection.allCases) { section in Button { viewModel.section = section } label: { Label(LocalizedStringKey(section.titleKey), systemImage: symbol(section)).frame(maxWidth: .infinity, alignment: .leading) }.buttonStyle(.plain).padding(10).background(viewModel.section == section ? TerminalTokens.phosphor.opacity(0.12) : .clear) }; Spacer(); Label("gym.manualOnly", systemImage: "hand.raised").font(.caption).foregroundStyle(TerminalTokens.phosphorMuted).padding(10) }.frame(width: 190).background(TerminalTokens.surface.opacity(0.45)) }
    private func symbol(_ section: GymSection) -> String { switch section { case .overview: "chart.line.uptrend.xyaxis"; case .plans: "list.bullet.clipboard"; case .exercises: "figure.strengthtraining.traditional"; case .schedule: "calendar"; case .history: "clock.arrow.circlepath" } }
    private var toolbar: some View { HStack { Image(systemName: "magnifyingglass"); TextField("gym.search", text: $viewModel.searchText).textFieldStyle(.plain).focused($searchFocused); Picker("gym.sort", selection: $viewModel.sort) { ForEach(GymSort.allCases) { Text(LocalizedStringKey($0.titleKey)).tag($0) } }.frame(width: 120); if viewModel.section == .plans { Toggle("gym.filter.activePlans", isOn: $viewModel.activePlansOnly).toggleStyle(.checkbox) } else if viewModel.section == .schedule { Toggle("gym.filter.incompleteSchedule", isOn: $viewModel.incompleteScheduleOnly).toggleStyle(.checkbox) }; Button(action: createNew) { Label("action.new", systemImage: "plus") }.buttonStyle(TerminalPrimaryButtonStyle()).disabled(viewModel.section == .overview) }.padding(.horizontal, 12).frame(height: 52).background(TerminalTokens.surface.opacity(0.35)) }
    @ViewBuilder private var content: some View { switch viewModel.section { case .overview: overview; case .plans: plansList; case .exercises: exerciseList; case .schedule: scheduleList; case .history: historyList } }

    private var overview: some View { ScrollView { VStack(alignment: .leading, spacing: 14) { LazyVGrid(columns: Array(repeating: GridItem(.flexible()), count: 4), spacing: 10) { metric("gym.metric.sessions", "\(summary.sessionCount)", "checkmark.circle"); metric("gym.metric.minutes", "\(summary.totalMinutes)", "timer"); metric("gym.metric.volume", summary.totalVolume.formatted(.number.precision(.fractionLength(1))), "scalemass"); metric("gym.metric.next", summary.nextSession?.formatted(date: .abbreviated, time: .shortened) ?? "—", "calendar.badge.clock") }; Text("gym.volume.help").font(.caption).foregroundStyle(TerminalTokens.phosphorMuted); Text("gym.progress.title").font(.headline); ForEach(exercises) { exercise in HStack { Text(exercise.name); Spacer(); Text(String(format: String(localized: "gym.best.format"), viewModel.personalBest(logs: logs, exerciseID: exercise.id))).monospacedDigit() }.padding(8).background(TerminalTokens.surface.opacity(0.6)) } }.padding(16) } }
    private func metric(_ key: String, _ value: String, _ symbol: String) -> some View { VStack(alignment: .leading, spacing: 6) { Label(LocalizedStringKey(key), systemImage: symbol).font(.caption).foregroundStyle(TerminalTokens.phosphorMuted); Text(value).font(.title2).fontWeight(.bold).monospacedDigit() }.frame(maxWidth: .infinity, alignment: .leading).padding(12).background(TerminalTokens.surface).overlay(RoundedRectangle(cornerRadius: 3).stroke(TerminalTokens.border)) }
    private var plansList: some View {
        let rows = viewModel.filteredPlans(plans)
        return Group {
            if rows.isEmpty {
                empty("gym.plans.empty", "gym.plans.empty.message", .plan(nil))
            } else {
                List {
                    ForEach(rows) { plan in
                        Section {
                            Button { editor = .plan(plan.id) } label: {
                                HStack {
                                    Image(systemName: plan.isActive ? "checkmark.circle" : "pause.circle")
                                    VStack(alignment: .leading) {
                                        Text(plan.name).fontWeight(.semibold)
                                        Text(plan.goal).font(.caption).foregroundStyle(TerminalTokens.phosphorMuted)
                                    }
                                    Spacer()
                                    if let next = plan.nextSessionDate { Text(next, style: .date) }
                                }
                            }
                            .buttonStyle(.plain)
                            .contextMenu {
                                Button("action.edit") { editor = .plan(plan.id) }
                                Button("action.delete", role: .destructive) { deletion = .plan(plan.id) }
                            }
                            ForEach(plannedExercises.filter { $0.planID == plan.id }.sorted { $0.order < $1.order }) { link in
                                let exercise = exercises.first { $0.id == link.exerciseID }
                                HStack {
                                    Image(systemName: "arrow.turn.down.right")
                                    Text(exercise?.name ?? String(localized: "gym.exercise.missing"))
                                    Spacer()
                                    Text("\(link.targetSets)×\(link.targetReps) @ \(link.targetWeight.formatted()) kg")
                                    Button("action.edit") { editor = .planExercise(link.id, plan.id) }.buttonStyle(.plain)
                                    Button("action.delete", role: .destructive) { deletion = .planExercise(link.id, plan.id) }.buttonStyle(.plain)
                                }
                            }
                            Button { editor = .planExercise(nil, plan.id) } label: {
                                Label("gym.plan.addExercise", systemImage: "plus")
                            }
                            .buttonStyle(.plain)
                            .disabled(exercises.isEmpty)
                        }
                    }
                }
                .listStyle(.inset)
                .scrollContentBackground(.hidden)
            }
        }
    }
    private var exerciseList: some View { let rows = viewModel.filteredExercises(exercises); return Group { if rows.isEmpty { empty("gym.exercises.empty", "gym.exercises.empty.message", .exercise(nil)) } else { List(rows) { item in Button { editor = .exercise(item.id) } label: { HStack { Image(systemName: "dumbbell"); VStack(alignment: .leading) { Text(item.name).fontWeight(.semibold); Text(item.muscleGroup).font(.caption).foregroundStyle(TerminalTokens.phosphorMuted) }; Spacer(); Text("\(item.defaultSets)×\(item.defaultReps)"); Text("\(item.defaultWeight.formatted()) kg") }.padding(.vertical, 4) }.buttonStyle(.plain).contextMenu { Button("action.edit") { editor = .exercise(item.id) }; Button("action.delete", role: .destructive) { deletion = .exercise(item.id) } } }.listStyle(.inset).scrollContentBackground(.hidden) } } }
    private var scheduleList: some View { let rows = plannedSessions.filter { (!viewModel.incompleteScheduleOnly || !$0.isCompleted) && (viewModel.searchText.isEmpty || $0.note.localizedCaseInsensitiveContains(viewModel.searchText)) }.sorted { $0.date < $1.date }; return Group { if rows.isEmpty { empty("gym.schedule.empty", "gym.schedule.empty.message", .plannedSession(nil)) } else { List(rows) { item in Button { editor = .plannedSession(item.id) } label: { HStack { Image(systemName: item.isCompleted ? "checkmark.circle.fill" : "calendar.badge.clock"); VStack(alignment: .leading) { Text(plans.first(where: { $0.id == item.planID })?.name ?? String(localized: "gym.unassignedPlan")); Text(item.note).font(.caption).foregroundStyle(TerminalTokens.phosphorMuted) }; Spacer(); Text(item.date, style: .date); Text(item.date, style: .time) } }.buttonStyle(.plain).contextMenu { Button("action.edit") { editor = .plannedSession(item.id) }; Button("action.delete", role: .destructive) { deletion = .plannedSession(item.id) } } }.listStyle(.inset).scrollContentBackground(.hidden) } } }
    private var historyList: some View { let rows = viewModel.filteredSessions(sessions); return Group { if rows.isEmpty { empty("gym.history.empty", "gym.history.empty.message", .session(nil)) } else { List(rows) { item in Button { editor = .session(item.id) } label: { HStack { Image(systemName: "checkmark.seal"); VStack(alignment: .leading) { Text(item.title).fontWeight(.semibold); Text(item.note).font(.caption).foregroundStyle(TerminalTokens.phosphorMuted) }; Spacer(); Text(String(format: String(localized: "gym.minutes.format"), item.durationMinutes)); Text(item.date, style: .date) }.padding(.vertical, 4) }.buttonStyle(.plain).contextMenu { Button("action.edit") { editor = .session(item.id) }; Button("action.delete", role: .destructive) { deletion = .session(item.id) } } }.listStyle(.inset).scrollContentBackground(.hidden) } } }
    private func empty(_ title: String, _ message: String, _ target: GymEditorTarget) -> some View { TerminalEmptyState(titleKey: title, messageKey: message, actionKey: "action.new", action: { editor = target }) }
    private func createNew() { switch viewModel.section { case .plans: editor = .plan(nil); case .exercises: editor = .exercise(nil); case .schedule: editor = .plannedSession(nil); case .history: editor = .session(nil); case .overview: break } }
    @ViewBuilder private func editorView(_ target: GymEditorTarget) -> some View { switch target { case .plan(let id): PlanEditor(plan: plans.first { $0.id == id }, viewModel: viewModel); case .exercise(let id): ExerciseEditor(exercise: exercises.first { $0.id == id }, viewModel: viewModel); case .planExercise(let id, let planID): PlanExerciseEditor(link: plannedExercises.first { $0.id == id }, planID: planID, exercises: exercises); case .plannedSession(let id): PlannedSessionEditor(session: plannedSessions.first { $0.id == id }, plans: plans, viewModel: viewModel); case .session(let id): CompletedSessionEditor(session: sessions.first { $0.id == id }, plans: plans, exercises: exercises, viewModel: viewModel) } }
    private func confirmDelete() { guard let deletion else { return }; do { switch deletion { case .plan(let id): if let value = plans.first(where: { $0.id == id }) { for link in plannedExercises where link.planID == value.id { context.delete(link) }; try viewModel.delete(value, context: context) }; case .exercise(let id): if let value = exercises.first(where: { $0.id == id }) { for link in plannedExercises where link.exerciseID == value.id { context.delete(link) }; try viewModel.delete(value, context: context) }; case .planExercise(let id, _): if let value = plannedExercises.first(where: { $0.id == id }) { try viewModel.delete(value, context: context) }; case .plannedSession(let id): if let value = plannedSessions.first(where: { $0.id == id }) { try viewModel.delete(value, context: context) }; case .session(let id): if let value = sessions.first(where: { $0.id == id }) { for log in logs where log.sessionID == value.id { context.delete(log) }; try viewModel.delete(value, context: context) } } } catch { viewModel.errorMessage = error.localizedDescription }; self.deletion = nil }
}

private enum GymEditorTarget: Identifiable { case plan(UUID?), exercise(UUID?), planExercise(UUID?, UUID), plannedSession(UUID?), session(UUID?); var id: String { switch self { case .plan(let id): "p\(id?.uuidString ?? "new")"; case .exercise(let id): "e\(id?.uuidString ?? "new")"; case .planExercise(let id, let plan): "l\(id?.uuidString ?? "new")\(plan)"; case .plannedSession(let id): "ps\(id?.uuidString ?? "new")"; case .session(let id): "s\(id?.uuidString ?? "new")" } } }

private struct PlanEditor: View { @Environment(\.modelContext) var context; let plan: WorkoutPlan?; @ObservedObject var viewModel: GymViewModel; @State var name: String; @State var goal: String; @State var active: Bool; @State var hasNext: Bool; @State var next: Date; init(plan: WorkoutPlan?, viewModel: GymViewModel) { self.plan = plan; self.viewModel = viewModel; _name = State(initialValue: plan?.name ?? ""); _goal = State(initialValue: plan?.goal ?? ""); _active = State(initialValue: plan?.isActive ?? true); _hasNext = State(initialValue: plan?.nextSessionDate != nil); _next = State(initialValue: plan?.nextSessionDate ?? .now) }; var body: some View { gymEditor(plan == nil ? "gym.plan.new" : "gym.plan.edit") { TextField("gym.plan.name", text: $name); TextField("gym.plan.goal", text: $goal); Toggle("gym.plan.active", isOn: $active); Toggle("gym.plan.hasNext", isOn: $hasNext); if hasNext { DatePicker("gym.plan.next", selection: $next) } } save: { try viewModel.savePlan(plan, name: name, goal: goal, active: active, nextDate: hasNext ? next : nil, context: context) } } }
private struct ExerciseEditor: View { @Environment(\.modelContext) var context; let exercise: ExerciseDefinition?; @ObservedObject var viewModel: GymViewModel; @State var name: String; @State var group: String; @State var sets: Int; @State var reps: Int; @State var weight: Double; init(exercise: ExerciseDefinition?, viewModel: GymViewModel) { self.exercise = exercise; self.viewModel = viewModel; _name = State(initialValue: exercise?.name ?? ""); _group = State(initialValue: exercise?.muscleGroup ?? ""); _sets = State(initialValue: exercise?.defaultSets ?? 3); _reps = State(initialValue: exercise?.defaultReps ?? 10); _weight = State(initialValue: exercise?.defaultWeight ?? 0) }; var body: some View { gymEditor(exercise == nil ? "gym.exercise.new" : "gym.exercise.edit") { TextField("gym.exercise.name", text: $name); TextField("gym.exercise.group", text: $group); Stepper("gym.exercise.sets \(sets)", value: $sets, in: 1...30); Stepper("gym.exercise.reps \(reps)", value: $reps, in: 1...100); TextField("gym.exercise.weight", value: $weight, format: .number) } save: { try viewModel.saveExercise(exercise, name: name, group: group, sets: sets, reps: reps, weight: weight, context: context) } } }
private struct PlanExerciseEditor: View { @Environment(\.modelContext) var context; let link: PlannedWorkoutExercise?; let planID: UUID; let exercises: [ExerciseDefinition]; @State var exerciseID: UUID?; @State var sets: Int; @State var reps: Int; @State var weight: Double; @State var order: Int; init(link: PlannedWorkoutExercise?, planID: UUID, exercises: [ExerciseDefinition]) { self.link = link; self.planID = planID; self.exercises = exercises; _exerciseID = State(initialValue: link?.exerciseID ?? exercises.first?.id); _sets = State(initialValue: link?.targetSets ?? 3); _reps = State(initialValue: link?.targetReps ?? 10); _weight = State(initialValue: link?.targetWeight ?? 0); _order = State(initialValue: link?.order ?? 0) }; var body: some View { gymEditor(link == nil ? "gym.planExercise.new" : "gym.planExercise.edit") { Picker("gym.exercise.name", selection: $exerciseID) { ForEach(exercises) { Text($0.name).tag(Optional($0.id)) } }; Stepper("gym.exercise.sets \(sets)", value: $sets, in: 1...30); Stepper("gym.exercise.reps \(reps)", value: $reps, in: 1...100); TextField("gym.exercise.weight", value: $weight, format: .number); Stepper("gym.planExercise.order \(order)", value: $order, in: 0...100) } save: { guard let exerciseID else { throw GymValidationError.nameRequired }; if let link { link.exerciseID = exerciseID; link.order = order; link.targetSets = sets; link.targetReps = reps; link.targetWeight = weight } else { context.insert(PlannedWorkoutExercise(planID: planID, exerciseID: exerciseID, order: order, targetSets: sets, targetReps: reps, targetWeight: weight)) }; try context.save() } } }
private struct PlannedSessionEditor: View { @Environment(\.modelContext) var context; let session: PlannedWorkoutSession?; let plans: [WorkoutPlan]; @ObservedObject var viewModel: GymViewModel; @State var planID: UUID?; @State var date: Date; @State var completed: Bool; @State var note: String; init(session: PlannedWorkoutSession?, plans: [WorkoutPlan], viewModel: GymViewModel) { self.session = session; self.plans = plans; self.viewModel = viewModel; _planID = State(initialValue: session?.planID); _date = State(initialValue: session?.date ?? .now); _completed = State(initialValue: session?.isCompleted ?? false); _note = State(initialValue: session?.note ?? "") }; var body: some View { gymEditor(session == nil ? "gym.schedule.new" : "gym.schedule.edit") { Picker("gym.plan.name", selection: $planID) { Text("gym.unassignedPlan").tag(UUID?.none); ForEach(plans) { Text($0.name).tag(Optional($0.id)) } }; DatePicker("gym.schedule.date", selection: $date); Toggle("gym.schedule.completed", isOn: $completed); TextField("gym.note", text: $note) } save: { try viewModel.savePlannedSession(session, planID: planID, date: date, completed: completed, note: note, context: context) } } }
private struct CompletedSessionEditor: View { @Environment(\.modelContext) var context; let session: WorkoutRecord?; let plans: [WorkoutPlan]; let exercises: [ExerciseDefinition]; @ObservedObject var viewModel: GymViewModel; @State var title: String; @State var date: Date; @State var duration: Int; @State var note: String; @State var planID: UUID?; @State var exerciseID: UUID?; @State var sets = 3; @State var reps = 10; @State var weight = 0.0; init(session: WorkoutRecord?, plans: [WorkoutPlan], exercises: [ExerciseDefinition], viewModel: GymViewModel) { self.session = session; self.plans = plans; self.exercises = exercises; self.viewModel = viewModel; _title = State(initialValue: session?.title ?? ""); _date = State(initialValue: session?.date ?? .now); _duration = State(initialValue: session?.durationMinutes ?? 45); _note = State(initialValue: session?.note ?? ""); _planID = State(initialValue: session?.planID); _exerciseID = State(initialValue: nil) }; var body: some View { gymEditor(session == nil ? "gym.session.new" : "gym.session.edit") { TextField("gym.session.title", text: $title); DatePicker("gym.session.date", selection: $date); Stepper("gym.session.duration \(duration)", value: $duration, in: 1...600); Picker("gym.plan.name", selection: $planID) { Text("gym.unassignedPlan").tag(UUID?.none); ForEach(plans) { Text($0.name).tag(Optional($0.id)) } }; Picker("gym.session.exercise", selection: $exerciseID) { Text("gym.session.noExercise").tag(UUID?.none); ForEach(exercises) { Text($0.name).tag(Optional($0.id)) } }; if exerciseID != nil { Stepper("gym.exercise.sets \(sets)", value: $sets, in: 1...30); Stepper("gym.exercise.reps \(reps)", value: $reps, in: 1...100); TextField("gym.exercise.weight", value: $weight, format: .number) }; TextField("gym.note", text: $note) } save: { try viewModel.saveCompletedSession(session, title: title, date: date, duration: duration, note: note, planID: planID, exerciseID: exerciseID, sets: sets, reps: reps, weight: weight, context: context) } } }

private extension View { func gymEditor<Fields: View>(_ title: String, @ViewBuilder fields: () -> Fields, save: @escaping () throws -> Void) -> some View { GymEditorShell(title: title, fields: fields(), save: save) } }
private struct GymEditorShell<Fields: View>: View { @Environment(\.dismiss) var dismiss; let title: String; let fields: Fields; let save: () throws -> Void; @State var error: String?; var body: some View { TerminalWindow { TerminalDialog(titleKey: title) { ScrollView { TerminalForm { fields } }.frame(minHeight: 240); if let error { Text(error).foregroundStyle(TerminalTokens.error) }; HStack { Spacer(); Button("action.cancel") { dismiss() }.buttonStyle(TerminalButtonStyle()); Button("action.save") { performSave() }.buttonStyle(TerminalPrimaryButtonStyle()) } }.padding() }.frame(width: 540, height: 500).onReceive(NotificationCenter.default.publisher(for: .nexusSave)) { _ in performSave() } }; private func performSave() { do { try save(); dismiss() } catch { self.error = error.localizedDescription } } }
