import SwiftUI
import SwiftData

struct FinanceView: View {
    @EnvironmentObject private var appState: AppState
    @Environment(\.modelContext) private var context
    @Query private var entries: [FinanceEntry]
    @Query private var debts: [DebtRecord]
    @Query private var budgets: [MonthlyBudget]
    @Query private var categories: [FinanceCategory]
    @Query private var recurring: [RecurringTransaction]
    @StateObject private var viewModel = FinanceViewModel()
    @AppStorage("finance.defaultCurrency") private var defaultCurrency = "TRY"
    @State private var editor: FinanceEditorTarget?
    @State private var deletion: FinanceEditorTarget?
    @FocusState private var searchFocused: Bool

    private var summary: FinanceSummary { viewModel.summary(entries: entries, debts: debts, budgets: budgets, month: viewModel.selectedMonth, currencyCode: defaultCurrency) }
    var body: some View {
        VStack(spacing: 0) {
            TerminalHeader(titleKey: "route.finance", subtitleKey: "finance.subtitle", onBack: appState.goHome)
            HStack(spacing: 0) { sidebar; Divider().overlay(TerminalTokens.border); VStack(spacing: 0) { toolbar; content } }
            if let error = viewModel.errorMessage { Label(error, systemImage: "xmark.octagon").foregroundStyle(TerminalTokens.error).padding(.horizontal, 12).frame(maxWidth: .infinity, minHeight: 28, alignment: .leading).background(TerminalTokens.surface) }
            else { TerminalStatusBar(messageKey: viewModel.statusMessageKey) }
        }
        .sheet(item: $editor) { target in editorView(target) }
        .confirmationDialog("delete.confirm.title", isPresented: Binding(get: { deletion != nil }, set: { if !$0 { deletion = nil } })) { Button("action.delete", role: .destructive, action: confirmDelete); Button("action.cancel", role: .cancel) { deletion = nil } } message: { Text("delete.confirm.message") }
        .onReceive(NotificationCenter.default.publisher(for: .nexusNewItem)) { _ in createNew() }
        .onReceive(NotificationCenter.default.publisher(for: .nexusFocusSearch)) { _ in searchFocused = true }
        .accessibilityIdentifier("finance.screen")
    }

    private var sidebar: some View { VStack(alignment: .leading, spacing: 4) { ForEach(FinanceSection.allCases) { section in Button { viewModel.section = section } label: { Label(LocalizedStringKey(section.titleKey), systemImage: financeSymbol(section)).frame(maxWidth: .infinity, alignment: .leading) }.buttonStyle(.plain).padding(10).background(viewModel.section == section ? TerminalTokens.phosphor.opacity(0.12) : .clear) }; Spacer(); Label("finance.localOnly", systemImage: "lock.shield").font(.caption).foregroundStyle(TerminalTokens.phosphorMuted).padding(10) }.frame(width: 190).background(TerminalTokens.surface.opacity(0.45)) }
    private func financeSymbol(_ section: FinanceSection) -> String { switch section { case .overview: "chart.bar"; case .transactions: "arrow.left.arrow.right"; case .debts: "person.2"; case .recurring: "repeat"; case .settings: "gearshape" } }
    private var toolbar: some View { HStack { Image(systemName: "magnifyingglass"); TextField("finance.search", text: $viewModel.searchText).textFieldStyle(.plain).focused($searchFocused); DatePicker("finance.month", selection: $viewModel.selectedMonth, displayedComponents: [.date]).labelsHidden(); if viewModel.section == .transactions { Picker("finance.filter", selection: $viewModel.typeFilter) { Text("filter.all").tag(FinanceTransactionType?.none); ForEach(FinanceTransactionType.allCases) { Text(LocalizedStringKey($0.titleKey)).tag(Optional($0)) } }.frame(width: 120); Picker("finance.sort", selection: $viewModel.sort) { ForEach(FinanceSort.allCases) { Text(LocalizedStringKey($0.titleKey)).tag($0) } }.frame(width: 120) } else if viewModel.section == .debts { Picker("finance.debt.status", selection: $viewModel.debtStatusFilter) { Text("filter.all").tag(DebtStatus?.none); ForEach(DebtStatus.allCases) { Text(LocalizedStringKey($0.titleKey)).tag(Optional($0)) } }.frame(width: 130) } else if viewModel.section == .recurring { Toggle("finance.recurring.activeOnly", isOn: $viewModel.recurringActiveOnly).toggleStyle(.checkbox) }; Button(action: createNew) { Label("action.new", systemImage: "plus") }.buttonStyle(TerminalPrimaryButtonStyle()).disabled(viewModel.section == .overview) }.padding(.horizontal, 12).frame(height: 52).background(TerminalTokens.surface.opacity(0.35)) }
    @ViewBuilder private var content: some View { switch viewModel.section { case .overview: overview; case .transactions: transactionList; case .debts: debtList; case .recurring: recurringList; case .settings: settings } }

    private var overview: some View { ScrollView { VStack(alignment: .leading, spacing: 14) { LazyVGrid(columns: Array(repeating: GridItem(.flexible()), count: 3), spacing: 10) { metric("finance.metric.income", summary.incomeMinorUnits, .success); metric("finance.metric.expense", summary.expenseMinorUnits, .warning); metric("finance.metric.balance", summary.balanceMinorUnits, summary.balanceMinorUnits >= 0 ? .success : .error); metric("finance.metric.budgetRemaining", summary.budgetRemainingMinorUnits, (summary.budgetRemainingMinorUnits ?? 0) >= 0 ? .neutral : .warning); metric("finance.metric.receivable", summary.receivableMinorUnits, .neutral); metric("finance.metric.payable", summary.payableMinorUnits, .warning) }; Label("finance.balance.help", systemImage: "info.circle").font(.caption).foregroundStyle(TerminalTokens.phosphorMuted); Divider().overlay(TerminalTokens.border); Text("finance.debt.net").font(.headline); Text(money(summary.netDebtPositionMinorUnits)).font(.title2).monospacedDigit(); Text("finance.debt.help").font(.caption).foregroundStyle(TerminalTokens.phosphorMuted) }.padding(16) } }
    private func metric(_ key: String, _ value: Int?, _ kind: TerminalStatusKind) -> some View { VStack(alignment: .leading, spacing: 6) { Label(LocalizedStringKey(key), systemImage: statusSymbol(kind)).font(.caption).foregroundStyle(kindColor(kind)); Text(value.map { money($0) } ?? "—").font(.title2).fontWeight(.bold).monospacedDigit() }.frame(maxWidth: .infinity, alignment: .leading).padding(12).background(TerminalTokens.surface).overlay(RoundedRectangle(cornerRadius: 3).stroke(TerminalTokens.border)) }
    private func statusSymbol(_ kind: TerminalStatusKind) -> String { switch kind { case .success: "checkmark.circle"; case .warning: "exclamationmark.triangle"; case .error: "xmark.octagon"; default: "circle" } }
    private func kindColor(_ kind: TerminalStatusKind) -> Color { switch kind { case .success: TerminalTokens.success; case .warning: TerminalTokens.warning; case .error: TerminalTokens.error; default: TerminalTokens.phosphor } }

    private var transactionList: some View { let rows = viewModel.filtered(entries); return Group { if rows.isEmpty { TerminalEmptyState(titleKey: "finance.transactions.empty", messageKey: "finance.transactions.empty.message", actionKey: "action.new", action: { editor = .entry(nil) }) } else { List(rows) { item in Button { editor = .entry(item.id) } label: { HStack { Image(systemName: item.type == .income ? "arrow.down.circle" : "arrow.up.circle").accessibilityLabel(Text(LocalizedStringKey(item.type.titleKey))); VStack(alignment: .leading) { Text(item.title).fontWeight(.semibold); Text(item.category.isEmpty ? String(localized: "finance.uncategorized") : item.category).font(.caption).foregroundStyle(TerminalTokens.phosphorMuted) }; Spacer(); Text(item.type == .expense ? "−\(money(item.normalizedAmountMinorUnits, currency: item.currencyCode))" : "+\(money(item.normalizedAmountMinorUnits, currency: item.currencyCode))").monospacedDigit(); Text(item.date, style: .date) }.padding(.vertical, 4) }.buttonStyle(.plain).contextMenu { Button("action.edit") { editor = .entry(item.id) }; Button("action.delete", role: .destructive) { deletion = .entry(item.id) } } }.listStyle(.inset).scrollContentBackground(.hidden) } } }
    private var debtList: some View { let rows = debts.filter { (viewModel.debtStatusFilter == nil || $0.status == viewModel.debtStatusFilter) && (viewModel.searchText.isEmpty || $0.counterparty.localizedCaseInsensitiveContains(viewModel.searchText) || $0.note.localizedCaseInsensitiveContains(viewModel.searchText)) }.sorted { ($0.dueDate ?? .distantFuture) < ($1.dueDate ?? .distantFuture) }; return Group { if rows.isEmpty { TerminalEmptyState(titleKey: "finance.debts.empty", messageKey: "finance.debts.empty.message", actionKey: "action.new", action: { editor = .debt(nil) }) } else { List(rows) { item in Button { editor = .debt(item.id) } label: { HStack { Image(systemName: item.direction == .owedByUser ? "arrow.up.right.circle" : "arrow.down.left.circle"); VStack(alignment: .leading) { Text(item.counterparty).fontWeight(.semibold); Text(LocalizedStringKey(item.direction.titleKey)).font(.caption).foregroundStyle(TerminalTokens.phosphorMuted) }; Spacer(); Text(money(abs(item.amountMinorUnits), currency: item.currencyCode)).monospacedDigit(); Text(LocalizedStringKey(item.status.titleKey)) }.padding(.vertical, 4) }.buttonStyle(.plain).contextMenu { Button("action.edit") { editor = .debt(item.id) }; Button("action.delete", role: .destructive) { deletion = .debt(item.id) } } }.listStyle(.inset).scrollContentBackground(.hidden) } } }
    private var recurringList: some View { let rows = recurring.filter { (!viewModel.recurringActiveOnly || $0.isActive) && (viewModel.searchText.isEmpty || $0.title.localizedCaseInsensitiveContains(viewModel.searchText)) }.sorted { $0.nextDate < $1.nextDate }; return Group { if rows.isEmpty { TerminalEmptyState(titleKey: "finance.recurring.empty", messageKey: "finance.recurring.empty.message", actionKey: "action.new", action: { editor = .recurring(nil) }) } else { List(rows) { item in Button { editor = .recurring(item.id) } label: { HStack { Image(systemName: item.isActive ? "repeat.circle.fill" : "pause.circle"); VStack(alignment: .leading) { Text(item.title).fontWeight(.semibold); Text(LocalizedStringKey(item.cadence.titleKey)).font(.caption).foregroundStyle(TerminalTokens.phosphorMuted) }; Spacer(); Text(money(item.amountMinorUnits, currency: item.currencyCode)); Text(item.nextDate, style: .date) }.padding(.vertical, 4) }.buttonStyle(.plain).contextMenu { Button("action.edit") { editor = .recurring(item.id) }; Button("action.delete", role: .destructive) { deletion = .recurring(item.id) } } }.listStyle(.inset).scrollContentBackground(.hidden) } } }
    private var settings: some View { ScrollView { VStack(alignment: .leading, spacing: 16) { Text("finance.settings.title").font(.title3).fontWeight(.bold); HStack { Text("finance.settings.currency"); TextField("finance.settings.currency", text: $defaultCurrency).frame(width: 90).onChange(of: defaultCurrency) { _, value in defaultCurrency = String(value.uppercased().prefix(3)) }; Spacer(); Button("finance.budget.edit") { editor = .budget }.buttonStyle(TerminalButtonStyle()) }; Divider().overlay(TerminalTokens.border); HStack { Text("finance.categories.title").font(.headline); Spacer(); Button("action.new") { editor = .category(nil) }.buttonStyle(TerminalButtonStyle()) }; ForEach(categories) { item in HStack { Text(item.name); Spacer(); Text(LocalizedStringKey(item.type.titleKey)); Button("action.delete", role: .destructive) { deletion = .category(item.id) }.buttonStyle(.plain) } }; Text("finance.settings.help").font(.caption).foregroundStyle(TerminalTokens.phosphorMuted) }.padding(16) } }
    private func money(_ minor: Int, currency: String? = nil) -> String { (Double(minor) / 100).formatted(.currency(code: currency ?? (defaultCurrency.isEmpty ? "TRY" : defaultCurrency))) }
    private func createNew() { switch viewModel.section { case .transactions: editor = .entry(nil); case .debts: editor = .debt(nil); case .recurring: editor = .recurring(nil); case .settings: editor = .category(nil); case .overview: break } }
    @ViewBuilder private func editorView(_ target: FinanceEditorTarget) -> some View { switch target { case .entry(let id): FinanceEntryEditor(entry: entries.first { $0.id == id }, viewModel: viewModel, currency: defaultCurrency); case .debt(let id): DebtEditor(debt: debts.first { $0.id == id }, viewModel: viewModel, currency: defaultCurrency); case .recurring(let id): RecurringEditor(record: recurring.first { $0.id == id }, viewModel: viewModel, currency: defaultCurrency); case .budget: BudgetEditor(budget: budgets.first { viewModel.monthInterval(containing: viewModel.selectedMonth).contains($0.monthStart) }, month: viewModel.selectedMonth, viewModel: viewModel, currency: defaultCurrency); case .category: CategoryEditor(viewModel: viewModel) } }
    private func confirmDelete() { guard let deletion else { return }; do { switch deletion { case .entry(let id): if let item = entries.first(where: { $0.id == id }) { try viewModel.delete(item, context: context) }; case .debt(let id): if let item = debts.first(where: { $0.id == id }) { try viewModel.delete(item, context: context) }; case .recurring(let id): if let item = recurring.first(where: { $0.id == id }) { try viewModel.delete(item, context: context) }; case .category(let id): if let item = categories.first(where: { $0.id == id }) { try viewModel.delete(item, context: context) }; case .budget: break } } catch { viewModel.errorMessage = error.localizedDescription }; self.deletion = nil }
}

private enum FinanceEditorTarget: Identifiable { case entry(UUID?), debt(UUID?), recurring(UUID?), budget, category(UUID?); var id: String { switch self { case .entry(let id): "e\(id?.uuidString ?? "new")"; case .debt(let id): "d\(id?.uuidString ?? "new")"; case .recurring(let id): "r\(id?.uuidString ?? "new")"; case .budget: "budget"; case .category(let id): "c\(id?.uuidString ?? "new")" } } }

private struct FinanceEntryEditor: View { @Environment(\.dismiss) var dismiss; @Environment(\.modelContext) var context; let entry: FinanceEntry?; @ObservedObject var viewModel: FinanceViewModel; @State var title: String; @State var amount: Double; @State var type: FinanceTransactionType; @State var date: Date; @State var category: String; let currency: String; @State var error: String?; init(entry: FinanceEntry?, viewModel: FinanceViewModel, currency: String) { self.entry = entry; self.viewModel = viewModel; self.currency = currency; _title = State(initialValue: entry?.title ?? ""); _amount = State(initialValue: Double(entry?.normalizedAmountMinorUnits ?? 0) / 100); _type = State(initialValue: entry?.type ?? .expense); _date = State(initialValue: entry?.date ?? .now); _category = State(initialValue: entry?.category ?? "") }; var body: some View { editorShell(entry == nil ? "finance.entry.new" : "finance.entry.edit") { TextField("finance.title", text: $title); TextField("finance.amount", value: $amount, format: .number); Picker("finance.type", selection: $type) { ForEach(FinanceTransactionType.allCases) { Text(LocalizedStringKey($0.titleKey)).tag($0) } }; DatePicker("finance.date", selection: $date); TextField("finance.category", text: $category) } save: { try viewModel.saveEntry(entry, title: title, amount: amount, type: type, date: date, currency: currency, category: category, context: context) } } }
private struct DebtEditor: View { @Environment(\.dismiss) var dismiss; @Environment(\.modelContext) var context; let debt: DebtRecord?; @ObservedObject var viewModel: FinanceViewModel; let currency: String; @State var counterparty: String; @State var amount: Double; @State var direction: DebtDirection; @State var status: DebtStatus; @State var hasDue: Bool; @State var due: Date; @State var note: String; init(debt: DebtRecord?, viewModel: FinanceViewModel, currency: String) { self.debt = debt; self.viewModel = viewModel; self.currency = currency; _counterparty = State(initialValue: debt?.counterparty ?? ""); _amount = State(initialValue: Double(debt?.amountMinorUnits ?? 0) / 100); _direction = State(initialValue: debt?.direction ?? .owedByUser); _status = State(initialValue: debt?.status ?? .outstanding); _hasDue = State(initialValue: debt?.dueDate != nil); _due = State(initialValue: debt?.dueDate ?? .now); _note = State(initialValue: debt?.note ?? "") }; var body: some View { editorShell(debt == nil ? "finance.debt.new" : "finance.debt.edit") { TextField("finance.debt.counterparty", text: $counterparty); TextField("finance.amount", value: $amount, format: .number); Picker("finance.debt.direction", selection: $direction) { ForEach(DebtDirection.allCases) { Text(LocalizedStringKey($0.titleKey)).tag($0) } }; Picker("finance.debt.status", selection: $status) { ForEach(DebtStatus.allCases) { Text(LocalizedStringKey($0.titleKey)).tag($0) } }; Toggle("finance.debt.hasDue", isOn: $hasDue); if hasDue { DatePicker("finance.debt.due", selection: $due) }; TextField("finance.note", text: $note) } save: { try viewModel.saveDebt(debt, counterparty: counterparty, amount: amount, currency: currency, direction: direction, dueDate: hasDue ? due : nil, status: status, note: note, context: context) } } }
private struct RecurringEditor: View { @Environment(\.dismiss) var dismiss; @Environment(\.modelContext) var context; let record: RecurringTransaction?; @ObservedObject var viewModel: FinanceViewModel; let currency: String; @State var title: String; @State var amount: Double; @State var type: FinanceTransactionType; @State var next: Date; @State var cadence: RecurrenceCadence; @State var active: Bool; @State var note: String; init(record: RecurringTransaction?, viewModel: FinanceViewModel, currency: String) { self.record = record; self.viewModel = viewModel; self.currency = currency; _title = State(initialValue: record?.title ?? ""); _amount = State(initialValue: Double(record?.amountMinorUnits ?? 0) / 100); _type = State(initialValue: record?.type ?? .expense); _next = State(initialValue: record?.nextDate ?? .now); _cadence = State(initialValue: record?.cadence ?? .monthly); _active = State(initialValue: record?.isActive ?? true); _note = State(initialValue: record?.note ?? "") }; var body: some View { editorShell(record == nil ? "finance.recurring.new" : "finance.recurring.edit") { TextField("finance.title", text: $title); TextField("finance.amount", value: $amount, format: .number); Picker("finance.type", selection: $type) { ForEach(FinanceTransactionType.allCases) { Text(LocalizedStringKey($0.titleKey)).tag($0) } }; DatePicker("finance.recurring.next", selection: $next); Picker("finance.recurring.cadence", selection: $cadence) { ForEach(RecurrenceCadence.allCases) { Text(LocalizedStringKey($0.titleKey)).tag($0) } }; Toggle("finance.recurring.active", isOn: $active); TextField("finance.note", text: $note) } save: { try viewModel.saveRecurring(record, title: title, amount: amount, currency: currency, type: type, nextDate: next, cadence: cadence, active: active, note: note, context: context) } } }
private struct BudgetEditor: View { @Environment(\.dismiss) var dismiss; @Environment(\.modelContext) var context; let budget: MonthlyBudget?; let month: Date; @ObservedObject var viewModel: FinanceViewModel; let currency: String; @State var amount: Double; init(budget: MonthlyBudget?, month: Date, viewModel: FinanceViewModel, currency: String) { self.budget = budget; self.month = month; self.viewModel = viewModel; self.currency = currency; _amount = State(initialValue: Double(budget?.amountMinorUnits ?? 0) / 100) }; var body: some View { editorShell("finance.budget.edit") { Text(month, style: .date); TextField("finance.amount", value: $amount, format: .number) } save: { try viewModel.saveBudget(budget, amount: amount, month: month, currency: currency, context: context) } } }
private struct CategoryEditor: View { @Environment(\.dismiss) var dismiss; @Environment(\.modelContext) var context; @ObservedObject var viewModel: FinanceViewModel; @State var name = ""; @State var type: FinanceTransactionType = .expense; var body: some View { editorShell("finance.category.new") { TextField("finance.category", text: $name); Picker("finance.type", selection: $type) { ForEach(FinanceTransactionType.allCases) { Text(LocalizedStringKey($0.titleKey)).tag($0) } } } save: { try viewModel.saveCategory(name: name, type: type, context: context) } } }

private extension View {
    func editorShell<Fields: View>(_ title: String, @ViewBuilder fields: () -> Fields, save: @escaping () throws -> Void) -> some View {
        FinanceEditorShell(title: title, fields: fields(), save: save)
    }
}
private struct FinanceEditorShell<Fields: View>: View { @Environment(\.dismiss) var dismiss; let title: String; let fields: Fields; let save: () throws -> Void; @State private var error: String?; var body: some View { TerminalWindow { TerminalDialog(titleKey: title) { TerminalForm { fields }.frame(minHeight: 220); if let error { Text(error).foregroundStyle(TerminalTokens.error) }; HStack { Spacer(); Button("action.cancel") { dismiss() }.buttonStyle(TerminalButtonStyle()); Button("action.save") { performSave() }.buttonStyle(TerminalPrimaryButtonStyle()) } }.padding() }.frame(width: 520, height: 460).onReceive(NotificationCenter.default.publisher(for: .nexusSave)) { _ in performSave() } }; private func performSave() { do { try save(); dismiss() } catch { self.error = error.localizedDescription } } }
